### ISSUE TITLE
Upgrading from 5.5 to 5.7 -  What is best practice?

### ISSUE THREAD

**Issue by cfoskin** [sclorg/mysql-container#209]
When running a 5.5  pod on openshift, what is the procedure for performing an upgrade to version 5.7? Basically I am looking at upgrading but just replacing the image with the 5.7 version will not work due to changes that need to be made to tables etc.

**Comment by hhorak** [comment]
Upstream only supports upgrading from the previous version, so when going from 5.5, you need to upgrade to 5.6 first, and only then to 5.7.

**Comment by hhorak** [comment]
Some more upstream documentation is in https://dev.mysql.com/doc/refman/5.7/en/upgrading-strategies.html.

**Comment by hhorak** [comment]
E.g. running `mysql_ssl_rsa_setup` if own SSL config is not provided is one thing. Maybe as a back-up also support extensions using `/docker-entrypoint-initdb.d`, since otherwise the containers are pretty much compatible in basic features. An interesting feature is also `MYSQL_ONETIME_PASSWORD`, that makes the root password expired if set, although it's not clear to me what is the use case of this one.

**Comment by phracek** [comment]
Closing this issue as upgrade from 5.5 -> 5.7 was deprecated a long time ago. Currently only 8.0 version is supported.
We do not have capacity to fix this issue.

Feel free to re-open it, in case you want it.
Closing it.
